services:

  mlflow-server:
    image: python:3.10-slim
    container_name: mlflow-server
    working_dir: /mlflow
    volumes:
      - mlflow-data:/mlflow
    ports:
      - "5000:5000"
    networks:
      - mlops-network
    command: >
      bash -c "pip install mlflow -q &&
               mlflow server
               --host 0.0.0.0
               --port 5000
               --backend-store-uri sqlite:///mlflow.db
               --default-artifact-root /mlflow/artifacts
               --allowed-hosts '*'
               --cors-allowed-origins '*'"

  api-service-1:
    build: .
    container_name: fraud-detection-api-1
    ports:
      - "8001:8000"
    networks:
      - mlops-network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server

  api-service-2:
    build: .
    container_name: fraud-detection-api-2
    ports:
      - "8002:8000"
    networks:
      - mlops-network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server

  api-service-3:
    build: .
    container_name: fraud-detection-api-3
    ports:
      - "8003:8000"
    networks:
      - mlops-network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    depends_on:
      - mlflow-server

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - mlops-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_alerts.yml:/etc/prometheus/prometheus_alerts.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mlops-network
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  mlops-network:
    driver: bridge

volumes:
  mlflow-data:
  model-data:
  prometheus-data:
  grafana-data: